// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CartComponent_AddToCart_FullMethodName = "/CartComponent/AddToCart"
)

// CartComponentClient is the client API for CartComponent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartComponentClient interface {
	AddToCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*CartResponse, error)
}

type cartComponentClient struct {
	cc grpc.ClientConnInterface
}

func NewCartComponentClient(cc grpc.ClientConnInterface) CartComponentClient {
	return &cartComponentClient{cc}
}

func (c *cartComponentClient) AddToCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, CartComponent_AddToCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartComponentServer is the server API for CartComponent service.
// All implementations must embed UnimplementedCartComponentServer
// for forward compatibility.
type CartComponentServer interface {
	AddToCart(context.Context, *CartRequest) (*CartResponse, error)
	mustEmbedUnimplementedCartComponentServer()
}

// UnimplementedCartComponentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartComponentServer struct{}

func (UnimplementedCartComponentServer) AddToCart(context.Context, *CartRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedCartComponentServer) mustEmbedUnimplementedCartComponentServer() {}
func (UnimplementedCartComponentServer) testEmbeddedByValue()                       {}

// UnsafeCartComponentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartComponentServer will
// result in compilation errors.
type UnsafeCartComponentServer interface {
	mustEmbedUnimplementedCartComponentServer()
}

func RegisterCartComponentServer(s grpc.ServiceRegistrar, srv CartComponentServer) {
	// If the following call pancis, it indicates UnimplementedCartComponentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartComponent_ServiceDesc, srv)
}

func _CartComponent_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartComponentServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartComponent_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartComponentServer).AddToCart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CartComponent_ServiceDesc is the grpc.ServiceDesc for CartComponent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartComponent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CartComponent",
	HandlerType: (*CartComponentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToCart",
			Handler:    _CartComponent_AddToCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}
