// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CartItems     []*CartRequest_CartItem `protobuf:"bytes,1,rep,name=cartItems,proto3" json:"cartItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartRequest) Reset() {
	*x = CartRequest{}
	mi := &file_api_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequest) ProtoMessage() {}

func (x *CartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequest.ProtoReflect.Descriptor instead.
func (*CartRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *CartRequest) GetCartItems() []*CartRequest_CartItem {
	if x != nil {
		return x.CartItems
	}
	return nil
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartID        uint32                 `protobuf:"varint,1,opt,name=cartID,proto3" json:"cartID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_api_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{1}
}

func (x *CartResponse) GetCartID() uint32 {
	if x != nil {
		return x.CartID
	}
	return 0
}

type CartRequest_CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     uint32                 `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartRequest_CartItem) Reset() {
	*x = CartRequest_CartItem{}
	mi := &file_api_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartRequest_CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequest_CartItem) ProtoMessage() {}

func (x *CartRequest_CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequest_CartItem.ProtoReflect.Descriptor instead.
func (*CartRequest_CartItem) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CartRequest_CartItem) GetProductID() uint32 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *CartRequest_CartItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api/service.proto\"\x88\x01\n" +
	"\vCartRequest\x123\n" +
	"\tcartItems\x18\x01 \x03(\v2\x15.CartRequest.CartItemR\tcartItems\x1aD\n" +
	"\bCartItem\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\rR\tproductID\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"&\n" +
	"\fCartResponse\x12\x16\n" +
	"\x06cartID\x18\x01 \x01(\rR\x06cartID2;\n" +
	"\rCartComponent\x12*\n" +
	"\tAddToCart\x12\f.CartRequest\x1a\r.CartResponse\"\x00B\x1eZ\x1chomework/internal/grpc/protob\x06proto3"

var (
	file_api_service_proto_rawDescOnce sync.Once
	file_api_service_proto_rawDescData []byte
)

func file_api_service_proto_rawDescGZIP() []byte {
	file_api_service_proto_rawDescOnce.Do(func() {
		file_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)))
	})
	return file_api_service_proto_rawDescData
}

var file_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_service_proto_goTypes = []any{
	(*CartRequest)(nil),          // 0: CartRequest
	(*CartResponse)(nil),         // 1: CartResponse
	(*CartRequest_CartItem)(nil), // 2: CartRequest.CartItem
}
var file_api_service_proto_depIdxs = []int32{
	2, // 0: CartRequest.cartItems:type_name -> CartRequest.CartItem
	0, // 1: CartComponent.AddToCart:input_type -> CartRequest
	1, // 2: CartComponent.AddToCart:output_type -> CartResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
		MessageInfos:      file_api_service_proto_msgTypes,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
